// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-TRiyg1XPoPMg3RPIjOlPkUuXWqeR75Q',
    appId: '1:843511099589:web:6700e063d1438e815840ac',
    messagingSenderId: '843511099589',
    projectId: 'clubnest-5c540',
    authDomain: 'clubnest-5c540.firebaseapp.com',
    storageBucket: 'clubnest-5c540.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCI3_ab_kTrsqGrtO9P5oGsjM8fWV8FesE',
    appId: '1:843511099589:android:154cc3e12873fc685840ac',
    messagingSenderId: '843511099589',
    projectId: 'clubnest-5c540',
    storageBucket: 'clubnest-5c540.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBQnWJGbV1ThSp8PUf90a0TvfH3lyYWUtU',
    appId: '1:843511099589:ios:f53ae9ff6dfb52325840ac',
    messagingSenderId: '843511099589',
    projectId: 'clubnest-5c540',
    storageBucket: 'clubnest-5c540.firebasestorage.app',
    iosBundleId: 'com.example.clubnest',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBQnWJGbV1ThSp8PUf90a0TvfH3lyYWUtU',
    appId: '1:843511099589:ios:f53ae9ff6dfb52325840ac',
    messagingSenderId: '843511099589',
    projectId: 'clubnest-5c540',
    storageBucket: 'clubnest-5c540.firebasestorage.app',
    iosBundleId: 'com.example.clubnest',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-TRiyg1XPoPMg3RPIjOlPkUuXWqeR75Q',
    appId: '1:843511099589:web:2828e67641e76f745840ac',
    messagingSenderId: '843511099589',
    projectId: 'clubnest-5c540',
    authDomain: 'clubnest-5c540.firebaseapp.com',
    storageBucket: 'clubnest-5c540.firebasestorage.app',
  );

}